set(Python3_VERSION_MAJOR      3)
set(Python3_VERSION_MINOR      8)
set(Python3_VERSION_PATCH      10)
# eg. Python3_VERSION = '3.8.10'
set(Python3_VERSION
  ${Python3_VERSION_MAJOR}.${Python3_VERSION_MINOR}.${Python3_VERSION_PATCH})

set(PACKAGE_VERSION ${Python3_VERSION})
set(PACKAGE_VERSION_MAJOR ${Python3_VERSION_MAJOR})
set(PACKAGE_VERSION_MINOR ${Python3_VERSION_MINOR})

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
