#!/bin/bash

# eg.: ' 16:09:36 up 28 min,  1 user, <...>' => '28 min'
# uptm=$(uptime | sed -E "s|.+ up ([^,]+),[0-9 ]+user.+|\1|")

#echo " ${USER}${uptm} "
echo "${USER}"
echo "${USER}"


if [[ $(id -u) -eq 0 ]]; then
  exit 33
fi
